apiVersion: v1
kind: Pod
metadata:
  name: pod-week-11-exam
  labels:
    app: web
spec:
  containers:
  - name: image-week-11-exam
    image: yakov234/week_11_exam:v1
    ports:
    - containerPort: 8080
